<?php

use Illuminate\Database\Seeder;

class AdreseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('adrese')->truncate();

        DB::table('adrese')->insert(array(
            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kurzemes prospekts',
                'majas_nr' => '145',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1069',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Zolitudes iela',
                'majas_nr' => '52',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1029',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Lielirbes iela',
                'majas_nr' => '30',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1046',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Jurmalas gatve',
                'majas_nr' => '7',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1007',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Uzvaras bulvaris',
                'majas_nr' => '16',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1048',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Jelgavas iela',
                'majas_nr' => '4',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Stacijas laukums',
                'majas_nr' => '1',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas bulvaris',
                'majas_nr' => '32',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas iela',
                'majas_nr' => '75',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1001',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas iela',
                'majas_nr' => '177',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas gatve',
                'majas_nr' => '214',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1039',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas gatve',
                'majas_nr' => '274',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1006',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas gatve',
                'majas_nr' => '372',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1006',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas gatve',
                'majas_nr' => '409',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1024',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Krisjana Berka iela',
                'majas_nr' => '6',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1067',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kleistu iela',
                'majas_nr' => '83',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1067',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Bullu iela',
                'majas_nr' => '45',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1067',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Dzirciema iela',
                'majas_nr' => '67',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1055',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Azenes iela',
                'majas_nr' => '24',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1048',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kronvalda bulvaris',
                'majas_nr' => '5',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1010',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Elizabetes iela',
                'majas_nr' => '78',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Augusta Deglava iela',
                'majas_nr' => '26',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1009',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Augusta Deglava iela',
                'majas_nr' => '55',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1035',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Andreja Saharova iela',
                'majas_nr' => '25',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1082',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Augusta Deglava iela',
                'majas_nr' => '160',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1021',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Tvaika iela',
                'majas_nr' => '2a',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1005',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Duntes iela',
                'majas_nr' => '18',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1005',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Ganibu dambis',
                'majas_nr' => '18',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1045',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Pulkveza Brieza iela',
                'majas_nr' => '31',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1045',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Zakusalas krastmala',
                'majas_nr' => '33',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Karla Ulmana gatve',
                'majas_nr' => '2',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Malu iela',
                'majas_nr' => '30',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1058',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Ozolciema iela',
                'majas_nr' => '10',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1058',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kleistu iela',
                'majas_nr' => '41',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1067',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Beberbeku iela',
                'majas_nr' => '30',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1029',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Brivibas gatve',
                'majas_nr' => '437a',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1024',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Garkalnes novads',
                'pilseta' => 'Bergi',
                'iela' => 'Rozu prospekts',
                'majas_nr' => '39',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1024',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Silikatu iela',
                'majas_nr' => '5',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Babites novads',
                'pilseta' => 'Spilve',
                'iela' => 'Puces iela',
                'majas_nr' => '6',
                'pagasts' => 'Babites pagasts',
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2101',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Stopinu novads',
                'pilseta' => 'Dreilini',
                'iela' => 'Smaidu iela',
                'majas_nr' => '19',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2130',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kaivas iela',
                'majas_nr' => '22',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1021',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Sniedzes iela',
                'majas_nr' => '25',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1015',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Jaunciema iela',
                'majas_nr' => '233',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1023',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => 'Marupe',
                'iela' => 'Veczarinu iela',
                'majas_nr' => '5',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2167',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Siltuma iela',
                'majas_nr' => '12',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1058',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Tiklu iela',
                'majas_nr' => '91',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Saktas iela',
                'majas_nr' => '83',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Sterstu iela',
                'majas_nr' => '84',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Rudolfa iela',
                'majas_nr' => '12',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Ainavas iela',
                'majas_nr' => '41',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Viksnes iela',
                'majas_nr' => '21',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Tirgonu iela',
                'majas_nr' => '76',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Gaizina iela',
                'majas_nr' => '93',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Gumijas iela',
                'majas_nr' => '13',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Sedas iela',
                'majas_nr' => '85',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Zaubes iela',
                'majas_nr' => '86',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1007',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Valnu iela',
                'majas_nr' => '46',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1007',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kalnciema iela',
                'majas_nr' => '51',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1007',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Muitas iela',
                'majas_nr' => '19',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1024',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Abolu iela',
                'majas_nr' => '32',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1024',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Balta iela',
                'majas_nr' => '35',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1024',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Delu iela',
                'majas_nr' => '62',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Ieriku iela',
                'majas_nr' => '13',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Liepkalna iela',
                'majas_nr' => '67',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Bajaru iela',
                'majas_nr' => '7',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2010',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Cesu iela',
                'majas_nr' => '98',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2010',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Indrupes iela',
                'majas_nr' => '23',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2010',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Vesetas iela',
                'majas_nr' => '77',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2010',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Nicgales iela',
                'majas_nr' => '72d',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2010',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Eglaines iela',
                'majas_nr' => '10',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Bruklenu iela',
                'majas_nr' => '42',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Zaubes iela',
                'majas_nr' => '46',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Laimdotas iela',
                'majas_nr' => '27d',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Pasta iela',
                'majas_nr' => '61',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Brivibas iela',
                'majas_nr' => '31',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jurmala',
                'iela' => 'Skarnu iela',
                'majas_nr' => '38',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2015',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Liepuziedi',
                'pasta_indekss' => 'LV-2103',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Klavas',
                'pasta_indekss' => 'LV-2103',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Bites novads',
                'pilseta' => 'Pinki',
                'iela' => 'Saldus iela',
                'majas_nr' => '11',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2107',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Bites novads',
                'pilseta' => 'Pinki',
                'iela' => 'Dzenu iela',
                'majas_nr' => '8',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2107',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Bites novads',
                'pilseta' => 'Pinki',
                'iela' => 'Robezu iela',
                'majas_nr' => '98',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2107',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Bites novads',
                'pilseta' => 'Pinki',
                'iela' => 'Lienes iela',
                'majas_nr' => '36',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2107',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Babites novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Babites pagasts',
                'majas_nosaukums' => 'Abelgravas',
                'pasta_indekss' => 'LV-2107',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => 'Kekava',
                'iela' => 'Vaveres iela',
                'majas_nr' => '41',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2111',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => 'Kekava',
                'iela' => 'Indrika iela',
                'majas_nr' => '5',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2111',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => 'Kekava',
                'iela' => 'Miera iela',
                'majas_nr' => '82',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2111',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => 'Balozi',
                'iela' => 'Vilandes iela',
                'majas_nr' => '38',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2112',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => 'Balozi',
                'iela' => 'Vesetas iela',
                'majas_nr' => '36',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2112',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => 'Balozi',
                'iela' => 'Kuldigas iela',
                'majas_nr' => '40',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2112',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Olaines novads',
                'pilseta' => 'Olaine',
                'iela' => 'Vidus iela',
                'majas_nr' => '37',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2114',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Salaspils novads',
                'pilseta' => 'Salaspils',
                'iela' => 'Koku iela',
                'majas_nr' => '71',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2118',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Salaspils novads',
                'pilseta' => 'Salaspils',
                'iela' => 'Elviras iela',
                'majas_nr' => '80c',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2118',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kekavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Daugmales pagasts',
                'majas_nosaukums' => 'Ozolkroni',
                'pasta_indekss' => 'LV-2124',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Baldones novads',
                'pilseta' => 'Baldone',
                'iela' => 'Talivalza iela',
                'majas_nr' => '20',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2125',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Baldones novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Baldones pagasts',
                'majas_nosaukums' => 'Laimzemes',
                'pasta_indekss' => 'LV-2125',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Olaines novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Olaines pagasts',
                'majas_nosaukums' => 'Gaujaskraces',
                'pasta_indekss' => 'LV-2127',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Olaines novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Olaines pagasts',
                'majas_nosaukums' => 'Cerini',
                'pasta_indekss' => 'LV-2127',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Stopinu novads',
                'pilseta' => 'Ulbroka',
                'iela' => 'Darza iela',
                'majas_nr' => '83',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2130',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Stopinu novads',
                'pilseta' => 'Ulbroka',
                'iela' => 'Ozolciema iela',
                'majas_nr' => '27',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2130',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ropazu novads',
                'pilseta' => 'Ropazi',
                'iela' => 'Eglaines iela',
                'majas_nr' => '34',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2135',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ropazu novads',
                'pilseta' => 'Ropazi',
                'iela' => 'Lapu iela',
                'majas_nr' => '16',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2135',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ropazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Klavas',
                'pasta_indekss' => 'LV-2135',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ropazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Rasaskalni',
                'pasta_indekss' => 'LV-2135',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ropazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Silulejas',
                'pasta_indekss' => 'LV-2135',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ropazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Strautini',
                'pasta_indekss' => 'LV-2135',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Incukalna novads',
                'pilseta' => 'Vangazi',
                'iela' => 'Kalna iela',
                'majas_nr' => '8c',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2136',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Incukalna novads',
                'pilseta' => 'Vangazi',
                'iela' => 'Gaizina iela',
                'majas_nr' => '23a',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2136',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Krimuldas pagasts',
                'majas_nosaukums' => 'Ziedonlejas',
                'pasta_indekss' => 'LV-2144',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Krimuldas pagasts',
                'majas_nosaukums' => 'Kalnini',
                'pasta_indekss' => 'LV-2144',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Krimuldas pagasts',
                'majas_nosaukums' => 'Laimzemes',
                'pasta_indekss' => 'LV-2144',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Siguldas novads',
                'pilseta' => 'Sigulda',
                'iela' => 'Jauna iela',
                'majas_nr' => '38',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2150',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Siguldas novads',
                'pilseta' => 'Sigulda',
                'iela' => 'Grislu iela',
                'majas_nr' => '16',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2150',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Siguldas novads',
                'pilseta' => 'Sigulda',
                'iela' => 'Zaubes iela',
                'majas_nr' => '73',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2150',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Malpils novads',
                'pilseta' => 'Malpils',
                'iela' => 'Skriveru iela',
                'majas_nr' => '50',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2152',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Malpils novads',
                'pilseta' => 'Malpils',
                'iela' => 'Piladzu iela',
                'majas_nr' => '25',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2152',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Malpils novads',
                'pilseta' => 'Malpils',
                'iela' => 'Zaubes iela',
                'majas_nr' => '46',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2152',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Malpils novads',
                'pilseta' => 'Malpils',
                'iela' => 'Saldus iela',
                'majas_nr' => '33',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2152',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Malpils novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Kalnini',
                'pasta_indekss' => 'LV-2152',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Siguldas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Allazu pagasts',
                'majas_nosaukums' => 'Kalnini',
                'pasta_indekss' => 'LV-2154',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Carnikavas novads',
                'pilseta' => 'Carnikava',
                'iela' => 'Starku iela',
                'majas_nr' => '59',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2163',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Carnikavas novads',
                'pilseta' => 'Carnikava',
                'iela' => 'Kramu iela',
                'majas_nr' => '7',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2163',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Carnikavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Bisudravas',
                'pasta_indekss' => 'LV-2163',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Carnikavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Dzintarvejs',
                'pasta_indekss' => 'LV-2163',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Carnikavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Klavas',
                'pasta_indekss' => 'LV-2163',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Baltezers',
                'iela' => 'Embutes iela',
                'majas_nr' => '55',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Adazi',
                'iela' => 'Lauku iela',
                'majas_nr' => '27',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Adazi',
                'iela' => 'Kramu iela',
                'majas_nr' => '40',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Kadaga',
                'iela' => 'Satekles iela',
                'majas_nr' => '49',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Kadaga',
                'iela' => 'Vigriezu iela',
                'majas_nr' => '64',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Kadaga',
                'iela' => 'Darzciema iela',
                'majas_nr' => '13',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Kadaga',
                'iela' => 'Dreilinu iela',
                'majas_nr' => '45',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Baltezers',
                'iela' => 'Gludas iela',
                'majas_nr' => '48',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Adazi',
                'iela' => 'Sedas iela',
                'majas_nr' => '59',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Kadaga',
                'iela' => 'Ikskiles iela',
                'majas_nr' => '44a',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Baltezers',
                'iela' => 'Vasku iela',
                'majas_nr' => '1',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Adazu novads',
                'pilseta' => 'Kadaga',
                'iela' => 'Talivalza iela',
                'majas_nr' => '18',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2164',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => 'Jaunmarupe',
                'iela' => 'Dreilinu iela',
                'majas_nr' => '95',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2166',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => 'Jaunmarupe',
                'iela' => 'Muitas iela',
                'majas_nr' => '67',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2166',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Bisudravas',
                'pasta_indekss' => 'LV-2166',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Dzintarvejs',
                'pasta_indekss' => 'LV-2166',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => 'Marupe',
                'iela' => 'Tirgonu iela',
                'majas_nr' => '9d',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2167',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => 'Marupe',
                'iela' => 'Jauniela',
                'majas_nr' => '81',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2167',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Marupes novads',
                'pilseta' => 'Marupe',
                'iela' => 'Rujienas iela',
                'majas_nr' => '54',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-2167',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jelgava',
                'iela' => 'Ilukstes iela',
                'majas_nr' => '75',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jelgava',
                'iela' => 'Ainavas iela',
                'majas_nr' => '52',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jelgava',
                'iela' => 'Gludas iela',
                'majas_nr' => '20',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jelgava',
                'iela' => 'Emmas iela',
                'majas_nr' => '1',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3003',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jelgava',
                'iela' => 'Dainas iela',
                'majas_nr' => '76',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3007',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Jelgava',
                'iela' => 'Liepkalna iela',
                'majas_nr' => '13',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3007',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Jelgavas novads',
                'pilseta' => 'Kalnciems',
                'iela' => 'Brivibas iela',
                'majas_nr' => '98',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Jelgavas novads',
                'pilseta' => 'Kalnciems',
                'iela' => 'Delu iela',
                'majas_nr' => '86',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ozolnieku novads',
                'pilseta' => 'Ozolnieki',
                'iela' => 'Rudolfa iela',
                'majas_nr' => '22',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3018',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Jelgavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Platones pagasts',
                'majas_nosaukums' => 'Ozoli',
                'pasta_indekss' => 'LV-3021',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Jelgavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Platones pagasts',
                'majas_nosaukums' => 'Trisozoli',
                'pasta_indekss' => 'LV-3021',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Jelgavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Platones pagasts',
                'majas_nosaukums' => 'Ozolkroni',
                'pasta_indekss' => 'LV-3021',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Jelgavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Platones pagasts',
                'majas_nosaukums' => 'Rasaskalni',
                'pasta_indekss' => 'LV-3021',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Tukuma novads',
                'pilseta' => 'Tukums',
                'iela' => 'Brivibas iela',
                'majas_nr' => '67',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3101',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Tukuma novads',
                'pilseta' => 'Tukums',
                'iela' => 'Ulbrokas iela',
                'majas_nr' => '95',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3101',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Tukuma novads',
                'pilseta' => 'Tukums',
                'iela' => 'Darza iela',
                'majas_nr' => '46',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3101',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Tukuma novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Dzukstes pagasts',
                'majas_nosaukums' => 'Trisozoli',
                'pasta_indekss' => 'LV-3147',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Tukuma novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Dzukstes pagasts',
                'majas_nosaukums' => 'Celalaimas',
                'pasta_indekss' => 'LV-3147',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Talsu novads',
                'pilseta' => 'Talsi',
                'iela' => 'Skriveru iela',
                'majas_nr' => '78',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3201',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Talsu novads',
                'pilseta' => 'Talsi',
                'iela' => 'Priekules iela',
                'majas_nr' => '61',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3201',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Talsu novads',
                'pilseta' => 'Talsi',
                'iela' => 'Priekules iela',
                'majas_nr' => '62',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3201',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Talsu novads',
                'pilseta' => 'Talsi',
                'iela' => 'Gludas iela',
                'majas_nr' => '83',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3201',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Talsu novads',
                'pilseta' => 'Talsi',
                'iela' => 'Akmenu iela',
                'majas_nr' => '16',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3201',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Talsu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Abavas pagasts',
                'majas_nosaukums' => 'Cerini',
                'pasta_indekss' => 'LV-3294',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Iecavas novads',
                'pilseta' => 'Iecava',
                'iela' => 'Vesetas iela',
                'majas_nr' => '96',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3913',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Iecavas novads',
                'pilseta' => 'Iecava',
                'iela' => 'Loma iela',
                'majas_nr' => '95',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3913',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Iecavas novads',
                'pilseta' => 'Iecava',
                'iela' => 'Lapsu iela',
                'majas_nr' => '64',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3913',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Iecavas novads',
                'pilseta' => 'Iecava',
                'iela' => 'Keguma iela',
                'majas_nr' => '42',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-3913',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Iecavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => NULL,
                'majas_nosaukums' => 'Dizavotini',
                'pasta_indekss' => 'LV-3913',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => 'Ledurga',
                'iela' => 'Vidus iela',
                'majas_nr' => '90',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => 'Ledurga',
                'iela' => 'Cesu iela',
                'majas_nr' => '63',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => 'Ledurga',
                'iela' => 'Priekules iela',
                'majas_nr' => '42',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => 'Ledurga',
                'iela' => 'Talivalza iela',
                'majas_nr' => '27',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Krimuldas novads',
                'pilseta' => 'Ledurga',
                'iela' => 'Akas iela',
                'majas_nr' => '95',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4012',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Batas iela',
                'majas_nr' => '76',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Indrupes iela',
                'majas_nr' => '3',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Baznicas iela',
                'majas_nr' => '76',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Jekabpils iela',
                'majas_nr' => '59',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Palidzibas iela',
                'majas_nr' => '48',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Lillijas iela',
                'majas_nr' => '74',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Vidrizi',
                'iela' => 'Griezes iela',
                'majas_nr' => '26',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4013',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Skulte',
                'iela' => 'Aizkraukles iela',
                'majas_nr' => '87',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4025',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Skulte',
                'iela' => 'Aizupes iela',
                'majas_nr' => '1',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4025',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Skulte',
                'iela' => 'Biesu iela',
                'majas_nr' => '97',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4025',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Skulte',
                'iela' => 'Sterstu iela',
                'majas_nr' => '78',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4025',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Skulte',
                'iela' => 'Isa iela',
                'majas_nr' => '4',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4025',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => 'Skulte',
                'iela' => 'Saites iela',
                'majas_nr' => '80',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-4025',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Vilkenes pagasts',
                'majas_nosaukums' => 'Dizavotini',
                'pasta_indekss' => 'LV-4050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Limbazu novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Vilkenes pagasts',
                'majas_nosaukums' => 'Kalnini',
                'pasta_indekss' => 'LV-4050',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ogres novads',
                'pilseta' => 'Ogre',
                'iela' => 'Krasta iela',
                'majas_nr' => '90',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5001',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ogres novads',
                'pilseta' => 'Ogre',
                'iela' => 'Ozolciema iela',
                'majas_nr' => '94a',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5001',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ogres novads',
                'pilseta' => 'Ogre',
                'iela' => 'Slepotaju iela',
                'majas_nr' => '10',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5001',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Tinuzu pagasts',
                'majas_nosaukums' => 'Dzintarplavas',
                'pasta_indekss' => 'LV-5001',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Tinuzu pagasts',
                'majas_nosaukums' => 'Klavas',
                'pasta_indekss' => 'LV-5001',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Ledmanes pagasts',
                'majas_nosaukums' => 'Laimzemes',
                'pasta_indekss' => 'LV-5011',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Ledmanes pagasts',
                'majas_nosaukums' => 'Sencukalns',
                'pasta_indekss' => 'LV-5011',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Ledmanes pagasts',
                'majas_nosaukums' => 'Bisudravas',
                'pasta_indekss' => 'LV-5011',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Ledmanes pagasts',
                'majas_nosaukums' => 'Strautini',
                'pasta_indekss' => 'LV-5011',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => 'Tinuzi',
                'iela' => 'Ezu iela',
                'majas_nr' => '22',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5015',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => 'Tinuzi',
                'iela' => 'Slepotaju iela',
                'majas_nr' => '69',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5015',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Keguma novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Rembates pagasts',
                'majas_nosaukums' => 'Ziedonlejas',
                'pasta_indekss' => 'LV-5016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Keguma novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Rembates pagasts',
                'majas_nosaukums' => 'Strautini',
                'pasta_indekss' => 'LV-5016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Keguma novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Rembates pagasts',
                'majas_nosaukums' => 'Liepuziedi',
                'pasta_indekss' => 'LV-5016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Keguma novads',
                'pilseta' => 'Kegums',
                'iela' => 'Pirts iela',
                'majas_nr' => '67',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5020',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => 'Ikskile',
                'iela' => 'Kaleju iela',
                'majas_nr' => '65',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5052',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => 'Ikskile',
                'iela' => 'Codes iela',
                'majas_nr' => '43',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5052',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ikskiles novads',
                'pilseta' => 'Ikskile',
                'iela' => 'Gumijas iela',
                'majas_nr' => '16',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5052',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Ogres novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Keipenes pagasts',
                'majas_nosaukums' => 'Menessdeli',
                'pasta_indekss' => 'LV-5062',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => 'Lielvarde',
                'iela' => 'Saktas iela',
                'majas_nr' => '73',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5070',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => 'Lielvarde',
                'iela' => 'Liepajas iela',
                'majas_nr' => '79',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5070',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Lielvardes novads',
                'pilseta' => 'Lielvarde',
                'iela' => 'Nitaures iela',
                'majas_nr' => '37',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5070',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kraslavas novads',
                'pilseta' => NULL,
                'iela' => NULL,
                'majas_nr' => NULL,
                'pagasts' => 'Indras pagasts',
                'majas_nosaukums' => 'Klavas',
                'pasta_indekss' => 'LV-5664',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kraslavas novads',
                'pilseta' => 'Saulkrasti',
                'iela' => 'Saites iela',
                'majas_nr' => '30',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5668',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kraslavas novads',
                'pilseta' => 'Saulkrasti',
                'iela' => 'Elizabetes iela',
                'majas_nr' => '4',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5668',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => 'Kraslavas novads',
                'pilseta' => 'Saulkrasti',
                'iela' => 'Elizabetes iela',
                'majas_nr' => '94',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-5668',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Kursu iela',
                'majas_nr' => '41',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1016',
            ),

            array(
                'valsts' => 'Latvija',
                'novads' => NULL,
                'pilseta' => 'Riga',
                'iela' => 'Eduarda Smilga iela',
                'majas_nr' => '27',
                'pagasts' => NULL,
                'majas_nosaukums' => NULL,
                'pasta_indekss' => 'LV-1004',
            ),

        ));

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

    }
}
